// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfwxexefflejdohohtjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmd3hleGVmZmxlamRvaG9odGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODg0ODIsImV4cCI6MjA2OTM2NDQ4Mn0.M6yG0yueiYAWEp4wxhLi56bJ7PlLW3g5v4xJPQ_HYQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});